### ISSUE TITLE
discord_js_1.IntentsBitField is not a constructor

### ISSUE THREAD

**Issue by prosilentgamer2** [watchdogsrox/splite#36]
2022-09-11 23:35:17 - info [app.js]: Initializing...
/home/Bot/node_modules/discord-player/dist/Player.js:46
        if (this.client?.options?.intents && !new discord_js_1.IntentsBitField(this.client?.options?.intents).has(discord_js_1.IntentsBitField.Flags.GuildVoiceStates)) {
                                              ^

TypeError: discord_js_1.IntentsBitField is not a constructor
    at new Player (/home/Bot/node_modules/discord-player/dist/Player.js:46:47)
    at new Client (/home/Bot/src/Client.js:53:23)
    at Object.<anonymous> (/home/Bot/app.js:15:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

**Comment by AdroidNoodle** [comment]
Changing the [`discord-player`](https://www.npmjs.com/package/discord-player) package version from **5.3.2** to **3.0.0** in `/package.json` seems to have fixed the issue.

**Comment by 416rehman** [comment]
> Changing the [`discord-player`](https://www.npmjs.com/package/discord-player) package version from **5.3.2** to **3.0.0** in `/package.json` seems to have fixed the issue.

This was the issue, discord-player was not compatible with discord.js 13.

The bot has been updated to DiscordJS 14 with update [dd9442e](https://github.com/416rehman/splite/commit/dd9442e0bffa4f8cee8ed508b71b2e20da6ab627). And this issue should no longer exist.
