### ISSUE TITLE
Severe issue

### ISSUE THREAD

**Issue by PixelatedPurple** [watchdogsrox/splite#58]
When starting the bot everything loads fine until the following error code pops up in the console

```
TypeError: Command is not a constructor
    at Client.tryLoadCommand (/home/runner/Odin/src/Client.js:200:25)
    at /home/runner/Odin/src/Client.js:186:27
    at Array.forEach (<anonymous>)
    at /home/runner/Odin/src/Client.js:184:22
    at Array.forEach (<anonymous>)
    at Client.loadCommands (/home/runner/Odin/src/Client.js:182:59)
    at /home/runner/Odin/app.js:18:12
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
exit status 1
```

**Comment by PixelatedPurple** [comment]
Im currently attempting to find a fix for this issue but its got me stumped for the last few days
